name: Daily Telegram Reminder

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5 AM UTC (9 AM Gulf Standard Time)
  workflow_dispatch:      # Allows manual run from GitHub interface

jobs:
  send_reminders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pandas openpyxl requests

    - name: Run Telegram Reminder Script
      run: python main.py
